version: '1'
services:
  PostgreSQL:
    container_name: postgreSQL
    hostname: postgreSQL
    image: postgres:16.0-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: DotnetExam
      
  RabbitMq:
    image: rabbitmq:3-alpine
    container_name: RabbitMq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"

  MongoStorage:
    image: mongo:6-jammy
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
      
  Api:
    image: dotnetexamback
    container_name: dotnetexamback
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT:Production
      - ASPNETCORE_URLS=http://+:80
      - JwtSettings__Issuer=Issuer
      - JwtSettings__Audience=Audience
      - JwtSettings__SecretKey=SuperSecretKey26746t27jhbjchbsierubvsjhd
      - JwtSettings__AccessTokenLifetimeInMinutes=600
      - Application__DbConnectionString=Host=localhost;Port=5432;Database=DotnetExam;User Id=postgres;Password=1234;Include Error Detail=true;
      - Application__RabbitMqConnectionString=amqp://admin:admin@RabbitMq:5672
      - Application__MongoDbConnectionString=mongodb://mongodb:27017
    build:
      context: ./Itis.DotnetExam.Api.Web
      dockerfile: Dockerfile
    depends_on:
      - RabbitMq
      - MongoStorage
      - PostgreSQL
        
  Frontend:
    image: dotnetexamfront
    container_name: dotnetexamfront
    ports:
      - "3000:5173"
    build:
      context: ./TicTacToeFrontend
      dockerfile: Dockerfile